package Calculadora;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * @author Octávio Santos Lamounier
 */
public class code extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(code.class.getName());

    // ===== Estado da calculadora =====
    private double memoria = 0;
    private double valorAnterior = 0;
    private char operadorPendente = ' '; 
    private String bufferAtual = "0";
    private boolean prontoParaNovoNumero = true; 
    private boolean temPontoDecimal = false;
    private boolean ultimaAcaoFoiMrc = false;

    
    public code() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btn0 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnPonto = new javax.swing.JButton();
        btnOff = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnSoma = new javax.swing.JButton();
        btnSubtracao = new javax.swing.JButton();
        btnMultiplicacao = new javax.swing.JButton();
        btnDivisao = new javax.swing.JButton();
        btnRaiz = new javax.swing.JButton();
        btnPorcentagem = new javax.swing.JButton();
        btnMn = new javax.swing.JButton();
        btnMp = new javax.swing.JButton();
        btnMrc = new javax.swing.JButton();
        txfDisplay = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");

        btn0.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn0.setText("0");
        btn0.setActionCommand("Btn0");
        btn0.addActionListener((java.awt.event.ActionEvent evt) -> {
            btn0ActionPerformed(evt);
        });

        btn1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn1.setText("1");
        btn1.setActionCommand("btn1");
        btn1.addActionListener((java.awt.event.ActionEvent evt) -> {
            btn1ActionPerformed(evt);
        });

        btn2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn2.setText("2");
        btn2.setActionCommand("btn2");
        btn2.addActionListener((java.awt.event.ActionEvent evt) -> {
            btn2ActionPerformed(evt);
        });

        btn3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn3.setText("3");
        btn3.setActionCommand("btn3");
        btn3.addActionListener((java.awt.event.ActionEvent evt) -> {
            btn3ActionPerformed(evt);
        });

        btn4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn4.setText("4");
        btn4.setActionCommand("btn4");
        btn4.addActionListener((java.awt.event.ActionEvent evt) -> {
            btn4ActionPerformed(evt);
        });

        btn5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn5.setText("5");
        btn5.setActionCommand("btn5");
        btn5.addActionListener((java.awt.event.ActionEvent evt) -> {
            btn5ActionPerformed(evt);
        });

        btn6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn6.setText("6");
        btn6.setActionCommand("btn6");
        btn6.addActionListener((java.awt.event.ActionEvent evt) -> {
            btn6ActionPerformed(evt);
        });

        btn7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn7.setText("7");
        btn7.setActionCommand("btn7");
        btn7.addActionListener((java.awt.event.ActionEvent evt) -> {
            btn7ActionPerformed(evt);
        });

        btn8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn8.setText("8");
        btn8.setActionCommand("btn8");
        btn8.addActionListener((java.awt.event.ActionEvent evt) -> {
            btn8ActionPerformed(evt);
        });

        btn9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn9.setText("9");
        btn9.setActionCommand("btn9");
        btn9.addActionListener((java.awt.event.ActionEvent evt) -> {
            btn9ActionPerformed(evt);
        });

        btnPonto.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnPonto.setText(".");
        btnPonto.setActionCommand("btnPonto");
        btnPonto.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnPontoActionPerformed(evt);
        });

        btnOff.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnOff.setText("Off");
        btnOff.setActionCommand("btnOff");
        btnOff.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnOffActionPerformed(evt);
        });

        btnClear.setBackground(new java.awt.Color(0, 102, 102));
        btnClear.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnClear.setText("CE");
        btnClear.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnClearActionPerformed(evt);
        });

        btnIgual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIgual.setText("=");
        btnIgual.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnIgualActionPerformed(evt);
        });

        btnSoma.setBackground(new java.awt.Color(0, 102, 102));
        btnSoma.setText("+");
        btnSoma.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnSomaActionPerformed(evt);
        });

        btnSubtracao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnSubtracao.setText("-");
        btnSubtracao.setActionCommand("btnSubtracao");
        btnSubtracao.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnSubtracaoActionPerformed(evt);
        });

        btnMultiplicacao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnMultiplicacao.setText("x");
        btnMultiplicacao.setActionCommand("btnMultiplicacao");
        btnMultiplicacao.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnMultiplicacaoActionPerformed(evt);
        });

        btnDivisao.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnDivisao.setText("÷");
        btnDivisao.setActionCommand("btnDivisao");
        btnDivisao.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnDivisaoActionPerformed(evt);
        });

        btnRaiz.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnRaiz.setText("√");
        btnRaiz.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnRaizActionPerformed(evt);
        });

        btnPorcentagem.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnPorcentagem.setText("%");
        btnPorcentagem.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnPorcentagemActionPerformed(evt);
        });

        txfDisplay.setEditable(false);
        txfDisplay.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txfDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfDisplay.setText("0");

        btnMn.setBackground(new java.awt.Color(204, 204, 0));
        btnMn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnMn.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnMnActionPerformed(evt);
        });

        btnMp.setBackground(new java.awt.Color(204, 204, 0));
        btnMp.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnMp.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnMpActionPerformed(evt);
        });

        btnMrc.setBackground(new java.awt.Color(204, 204, 0));
        btnMrc.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnMrc.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnMrcActionPerformed(evt);
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MRC");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("M+");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("M-");


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOff, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDivisao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMultiplicacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSubtracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnMrc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMp, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txfDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMrc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOff, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSoma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>                        

    // ================== LÓGICA DA CALCULADORA ==================

    private void exibirValor(double valor) {
        if (valor == (long) valor && !Double.isInfinite(valor)) {
            txfDisplay.setText(String.valueOf((long) valor));
        } 
        else {
            txfDisplay.setText(String.valueOf(valor));
        }
    }

    private void exibirString(String str) {
        txfDisplay.setText(str);
    }

    private double calcular(double a, double b, char operador) {
        switch (operador) {
            case '+': return a + b;
            case '-': return a - b;
            case '*': return a * b;
            case '/': return a / b; 
            default: return b;
        }
    }

    private void aplicarOperador(char novoOperador) {
        ultimaAcaoFoiMrc = false;
        double valorAtual = Double.parseDouble(bufferAtual);

        if (operadorPendente != ' ' && !prontoParaNovoNumero) {
            if (operadorPendente == '/' && valorAtual == 0) {
                exibirString("Erro");
                resetarEstado();
                return;
            }
            valorAnterior = calcular(valorAnterior, valorAtual, operadorPendente);
            exibirValor(valorAnterior);
        } 
        else {
            valorAnterior = valorAtual;
        }

        operadorPendente = novoOperador;
        prontoParaNovoNumero = true;
        temPontoDecimal = false;
    }

    private void resetarEstado() {
        bufferAtual = "0";
        valorAnterior = 0;
        operadorPendente = ' ';
        prontoParaNovoNumero = true;
        temPontoDecimal = false;
    }

    private void digitoPressionado(String digito) {
        ultimaAcaoFoiMrc = false;
        
        if (prontoParaNovoNumero) {
            bufferAtual = digito;
            prontoParaNovoNumero = false;
        } 
        else if (bufferAtual.equals("0")) {
            bufferAtual = digito.equals("0") ? "0" : digito;
        } 
        else {
            bufferAtual += digito;
        }
        
        exibirString(bufferAtual);
    }

    
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {
        digitoPressionado("1");
    }

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {
        digitoPressionado("2");
    }

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {
        digitoPressionado("3");
    }

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {
        digitoPressionado("4");
    }

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {
        digitoPressionado("5");
    }

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {
        digitoPressionado("6");
    }

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {
        digitoPressionado("7");
    }

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {
        digitoPressionado("8");
    }

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {
        digitoPressionado("9");
    }

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {
        digitoPressionado("0");
    }

    
    private void btnPontoActionPerformed(java.awt.event.ActionEvent evt) {
        if (prontoParaNovoNumero) {
            bufferAtual = "0.";
            prontoParaNovoNumero = false;
            temPontoDecimal = true;
        } 
        else if (!temPontoDecimal) {
            bufferAtual += ".";
            temPontoDecimal = true;
        }
        exibirString(bufferAtual);
    }

    
    private void btnSomaActionPerformed(java.awt.event.ActionEvent evt) {
        aplicarOperador('+');
    }

    private void btnSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {
        aplicarOperador('-');
    }

    private void btnMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {
        aplicarOperador('*');
    }

    private void btnDivisaoActionPerformed(java.awt.event.ActionEvent evt) {
        aplicarOperador('/');
    }
    
    
    private void btnPorcentagemActionPerformed(java.awt.event.ActionEvent evt) {
        double valorAtual = Double.parseDouble(bufferAtual);
        double fracao = valorAtual / 100.0;

        double resultado;
        switch (operadorPendente) {
            case '+':
            case '-':
                resultado = calcular(valorAnterior, valorAnterior * fracao, operadorPendente);
                break;
            case '*':
            case '/':
                resultado = calcular(valorAnterior, fracao, operadorPendente);
                break;
            default:
                resultado = fracao;
        }

        exibirValor(resultado);
        bufferAtual = String.valueOf(resultado);
        
        valorAnterior = resultado;
        operadorPendente = ' ';
        prontoParaNovoNumero = true;
        temPontoDecimal = false;
    }

    private void btnRaizActionPerformed(java.awt.event.ActionEvent evt) {
        double valorAtual = Double.parseDouble(bufferAtual);
        if (valorAtual < 0) {
            exibirString("Erro");
            resetarEstado();
            return;
        }
        
        double resultado = Math.sqrt(valorAtual);
        
        exibirValor(resultado);
        bufferAtual = String.valueOf(resultado);
        
        prontoParaNovoNumero = true;
        temPontoDecimal = false;
    }

    
    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {
        if (operadorPendente == ' ') return;
        
        double valorAtual = Double.parseDouble(bufferAtual);

        if (operadorPendente == '/' && valorAtual == 0) {
            exibirString("Erro");
            resetarEstado();
            return;
        }

        double resultado = calcular(valorAnterior, valorAtual, operadorPendente);
        
        exibirValor(resultado);
        bufferAtual = String.valueOf(resultado);
        
        valorAnterior = resultado;
        operadorPendente = ' '; 
        prontoParaNovoNumero = true;
        temPontoDecimal = false;
    }

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {
        resetarEstado();
        exibirString(bufferAtual);
    }

    
    private void btnMpActionPerformed(java.awt.event.ActionEvent evt) {
        memoria += Double.parseDouble(bufferAtual);
        prontoParaNovoNumero = true;
    }

    private void btnMnActionPerformed(java.awt.event.ActionEvent evt) {
        memoria -= Double.parseDouble(bufferAtual);
        prontoParaNovoNumero = true;
    }
    
    private void btnMrcActionPerformed(java.awt.event.ActionEvent evt) {
        if (ultimaAcaoFoiMrc) memoria = 0;

        exibirValor(memoria);
        bufferAtual = String.valueOf(memoria);
        ultimaAcaoFoiMrc = !ultimaAcaoFoiMrc;

        prontoParaNovoNumero = true;
        temPontoDecimal = false;
    }

    
    private void btnOffActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new code().setVisible(true));
    }
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDivisao;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMn;
    private javax.swing.JButton btnMp;
    private javax.swing.JButton btnMrc;
    private javax.swing.JButton btnMultiplicacao;
    private javax.swing.JButton btnOff;
    private javax.swing.JButton btnPonto;
    private javax.swing.JButton btnPorcentagem;
    private javax.swing.JButton btnRaiz;
    private javax.swing.JButton btnSoma;
    private javax.swing.JButton btnSubtracao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txfDisplay;
    // End of variables declaration                   

}